apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: gyanictest 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gyanictest 
    spec:
      containers:
        - name: gyanictest 
          image: gyangodcontainerreg.azurecr.io/gyanictest
          ports:
          - containerPort: 3000