apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: gyangodgyanic 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gyangodgyanic 
    spec:
      containers:
        - name: gyangodgyanic 
          image: gyangodtestcontainerregistry.azurecr.io/gyangodgyanic
          ports:
          - containerPort: 3000