apiVersion : apps/v1
kind: Deployment
metadata:
  name: gyangodgyanic
spec:
  progressDeadlineSeconds: 2000
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  replicas: 1
  template:
    metadata:
      labels:
        app: gyangodgyanic
    spec:
      containers:
        - name: gyangodgyanic
          image: gyangodtestcontainerregistry.azurecr.io/gyangodgyanic
          ports:
          - containerPort: 3000
